name: Tests

on: [push]

jobs:
    run-php-tests:

        runs-on: ubuntu-latest

        steps:
            -   name: Git checkout Core
                uses: actions/checkout@v2

            -   name: Shutdown Ubuntu MySQL (comes with OS)
                run: sudo service mysql stop
                
            - run: |
                docker run --name mysql -e MYSQL_ROOT_PASSWORD=root -d mysql:5.7
                docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql

            -   name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: '7.2'
                    coverage: none

            -   name: Setup empty databases
                run: |
                    docker ps
                    mysql -h172.17.0.2 -uroot -proot
